# 用來檢查專案中的潛在問題的 GitHub Actions 工作流程(workflow)定義檔
#
# 編輯參考：
#
# * Workflow syntax for GitHub Actions - GitHub Docs
#   https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
name: Check potential problems in project
on:
  - push
jobs:
  check-using-precommit:
    name: Use pre-commit to check potential problems in project
    runs-on: ubuntu-20.04
    steps:
      - name: Check out content from repository
        uses: actions/checkout@v2

      - name: Install pre-commit
        run: pip3 install pre-commit

      # pre-commit github actions example
      # https://pre-commit.com/#github-actions-example
      - name: Detect GitHub Actions cache key for pre-commit
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: >-
          Load pre-commit cache in order to cut time of subsequent
          builds
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Use pre-commit to check potential problems in project files
        run: pre-commit run --all-files --color always
